In [17]:
number_of_students = 100
number_of_teachers = 60
#variable                                           

print(f"Number of students : {number_of_students}")
print(f"Number of teachers : {number_of_teachers}")
print(f"Total number of people : {number_of_students + number_of_teachers}")

Number of students : 100
Number of teachers : 60
Total number of people : 160

In [16]:
#datatype
#This is integer
num_of_people = 100
num_of_countries = 10
num_of_cars= 1000

#This is Float
height = 1.75
weight = 70.5
percentage = 90.5

#This is string
name = "Syahmi"
university = "Universiti Teknologi Petronas"
country = "Malaysia"

#This is Boolean
is_student = True
is_employed = False

print ("-----")
print ("Datatype")
print ("-----")
print ("This is Integer")
print (num_of_people)
print (num_of_countries)
print (num_of_cars)
print ("-----")
print ("This is Float")
print (height)
print (weight)
print (percentage)
print ("-----")
print("This is String")
print (name)
print (university)
print (country)
print ("-----")
print ("This is Boolean")
print (is_student)
print (is_employed)

-----
Datatype
-----
This is Integer
100
10
1000
-----
This is Float
1.75
70.5
90.5
-----
This is String
Syahmi
Universiti Teknologi Petronas
Malaysia
-----
This is Boolean
True
False

In [33]:
"""
String method
1. capitalize() --> Convert the first character of a String to uppercase
2. lower() ---> Convert all characters of a string to lowercase
3. upper() ---> Convert all characters of a string to uppercase
4. title() ---> Convert the first character of each word to uppercase
5. split() ---> Splits a string into a list of substrings
6. strip() ---> Removes leading and trailing whitespaces
7. replace() ---> Replaces a substring with another substring
"""
#capitalize()
name = "abdul"
print("capitalize()")
print("Input : name = abdul")
print("Output:")
print(name.capitalize())
print("---------------")
#lower()
name = "SYAHMI"
print("lower()")
print("input : name - SYAHMI")
print("Output:")
print(name.lower())
print("---------------")
#upper()
name ="syahmi"
print("upper()")
print("Input : name = syahmi")
print("Output:")
print(name.upper())
print("---------------")
#title()
some_title = "malaysia won the first bronze medal in olympics 2024"
print("title()")
print("input : some_title = malaysia won the first bronze medal in olympics 2024 ")
print("Output:")
print(some_title.title())
print("---------------")
#split()
text="nama saya Syahmi"
print("split()")
print("Input : text = nama saya Syahmi")
print("Output:")
print(text.split())
print("---------------")
#strip()
text="      Malaysia is the best country to live in        "
print("strip()")
print("Output:")
print(text.strip())
print("---------------")
#replace()
text=("Malaysia won Bronze")
print("replace()")
print("Output:")
print(text.replace("Bronze" , "Silver"))

capitalize()
Input : name = abdul
Output:
Abdul
---------------
lower()
input : name - SYAHMI
Output:
syahmi
---------------
upper()
Input : name = syahmi
Output:
SYAHMI
---------------
title()
input : some_title = malaysia won the first bronze medal in olympics 2024
Output:
Malaysia Won The First Bronze Medal In Olympics 2024
---------------
split()
Input : text = nama saya Syahmi
Output:
['nama', 'saya', 'Syahmi']
---------------
strip()
Output:
Malaysia is the best country to live in
---------------
replace()
Output:
Malaysia won Silver

In [ ]:
"""
Python Naming Convention :
1. snake_case ---> use for variables, modules, function
2. CamelCase / PascalCase ---> use for Classes
3. UPPERCASE (CONSTANT) ---> Anything Constant
"""